## 2.1. Data Manipulation

## 2.1.1. Getting Started

In [67]:
!pip install --upgrade pip torch numpy

  Using cached pip-23.3.2-py3-none-any.whl (2.1 MB)
  Attempting uninstall: pip
    Found existing installation: pip 23.0.1
    Uninstalling pip-23.0.1:
      Successfully uninstalled pip-23.0.1


In [4]:
import torch
import numpy as np

In [7]:
x = torch.arange(10, dtype=torch.float32)
x

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [10]:
x.numel()

10

In [12]:
x.shape

torch.Size([10])

In [18]:
X = x.reshape(2, -1)
X

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])

In [14]:
X.numel()

10

In [15]:
X[6]

IndexError: index 6 is out of bounds for dimension 0 with size 2

In [20]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [23]:
torch.randn((3, 4))

tensor([[ 0.1523,  0.0657, -1.3673, -0.2253],
        [ 1.0657, -1.2175,  0.1845,  0.9049],
        [ 1.4220,  0.6294,  0.2927,  0.7393]])

In [26]:
torch.tensor([[2, 1, 4, 3], [3, 5, 6, 1]], dtype=torch.float32)

tensor([[2., 1., 4., 3.],
        [3., 5., 6., 1.]])

## 2.1.2 Indexing and Slicing

In [29]:
X = torch.arange(20, dtype=torch.float32).reshape(-1, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [31]:
X[-1], X[1:3]

(tensor([16., 17., 18., 19.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [32]:
X[2, 1] = 9.5
X

tensor([[ 0.0000,  1.0000,  2.0000,  3.0000],
        [ 4.0000,  5.0000,  6.0000,  7.0000],
        [ 8.0000,  9.5000, 10.0000, 11.0000],
        [12.0000, 13.0000, 14.0000, 15.0000],
        [16.0000, 17.0000, 18.0000, 19.0000]])

In [33]:
X[:2, :] = 12
X

tensor([[12.0000, 12.0000, 12.0000, 12.0000],
        [12.0000, 12.0000, 12.0000, 12.0000],
        [ 8.0000,  9.5000, 10.0000, 11.0000],
        [12.0000, 13.0000, 14.0000, 15.0000],
        [16.0000, 17.0000, 18.0000, 19.0000]])

## 2.1.3. Operations

In [35]:
torch.exp(X)

tensor([[1.6275e+05, 1.6275e+05, 1.6275e+05, 1.6275e+05],
        [1.6275e+05, 1.6275e+05, 1.6275e+05, 1.6275e+05],
        [2.9810e+03, 1.3360e+04, 2.2026e+04, 5.9874e+04],
        [1.6275e+05, 4.4241e+05, 1.2026e+06, 3.2690e+06],
        [8.8861e+06, 2.4155e+07, 6.5660e+07, 1.7848e+08]])

In [36]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 4, 7, 8])

x + y

tensor([ 3.,  6., 11., 16.])

In [44]:
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
Y = torch.ones((3, 4))

torch.cat((X, Y), dim=1)

tensor([[ 0.,  1.,  2.,  3.,  1.,  1.,  1.,  1.],
        [ 4.,  5.,  6.,  7.,  1.,  1.,  1.,  1.],
        [ 8.,  9., 10., 11.,  1.,  1.,  1.,  1.]])

In [45]:
X <= Y

tensor([[ True,  True, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [48]:
X.sum(), X.reshape((-1,)).sum()

(tensor(66.), tensor(66.))

## 2.1.4. Broadcasting

In [50]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [51]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [52]:
x = torch.tensor([[0, 0], [1, 1], [2, 2]])
y = torch.tensor([[0, 1], [0, 1], [0, 1]])
x + y

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [53]:
a + b == x + y

tensor([[True, True],
        [True, True],
        [True, True]])

### 2.1.5. Saving Memory

In [62]:
Y = torch.arange(12)
print(f"before = {id(Y)}")
Y += 1
print(f"after = {id(Y)}")

before = 4538067200
after = 4538067200


In [ ]:
Y[:] = Y + 1

### 2.1.6. Conversion to Other Python Objects

In [68]:
X = torch.arange(12)

A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

RuntimeError: Numpy is not available

## 2.1.8. Exercises

In [71]:
X = torch.arange(3).reshape((3, 1, 1))
Y = torch.arange(2).reshape((1, 1, 2))

X, Y

(tensor([[[0]],
 
         [[1]],
 
         [[2]]]),
 tensor([[[0, 1]]]))

In [72]:
X + Y

tensor([[[0, 1]],

        [[1, 2]],

        [[2, 3]]])